# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.22
# 
# >> macros
# << macros

Name:       qt5-gstreamer
VCS:        gstreamer/qt-gstreamer#da929779804b1b3e8e0c8d08f17b0538722d0f96
Summary:    C++ bindings for GStreamer with a Qt-style API
Version:    1.0
Release:    1
Group:      System/Libraries
License:    LGPLv2+
URL:        http://gstreamer.freedesktop.org/modules/qt-gstreamer.html
Source0:    %{name}-%{version}.tar.gz
Requires(post): /sbin/ldconfig
Requires(postun): /sbin/ldconfig
BuildRequires:  cmake
BuildRequires:  bison
BuildRequires:  flex
BuildRequires:  boost-devel
BuildRequires:  pkgconfig(Qt5Gui)
BuildRequires:  pkgconfig(Qt5OpenGL)
BuildRequires:  pkgconfig(Qt5Qml)
BuildRequires:  pkgconfig(Qt5Quick)
BuildRequires:  pkgconfig(Qt5Test)
BuildRequires:  pkgconfig(glib-2.0)
BuildRequires:  pkgconfig(gstreamer-1.0)
BuildRequires:  pkgconfig(gstreamer-plugins-base-1.0)
BuildRequires:  doxygen

%description
QtGStreamer provides C++ bindings for GStreamer with a Qt-style
API, plus some helper classes for integrating GStreamer better
in Qt5 applications.

%package devel
Summary:    Header files and development documentation for %{name}
Group:      Development/Libraries
Requires:   %{name} = %{version}-%{release}
Requires:   %{name}%{?_isa} = %{version}-%{release}
Requires:   boost-devel%{?_isa}

%description devel
This package contains the header files and development documentation
for %{name}.

%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# CMAKE_INSTALL_LIBDIR specified due to
# https://bugzilla.redhat.com/show_bug.cgi?id=795542
%{cmake} \
-DCMAKE_INSTALL_LIBDIR:PATH=%{_lib} \
-DCMAKE_C_FLAGS="%{optflags}" \
-DCMAKE_CXX_FLAGS="%{optflags}" \
-DQT_VERSION=5 \
-DQTGSTREAMER_STATIC=OFF \
-DQTGSTREAMER_EXAMPLES=OFF \
-DQTGSTREAMER_TESTS=OFF \
-DQTGSTREAMER_CODEGEN=OFF \
-DUSE_GST_PLUGIN_DIR=ON \
-DUSE_QT_PLUGIN_DIR=OFF
# << build pre

make %{?jobs:-j%jobs}

# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
# << install pre
%make_install

# >> install post
# << install post

%post -p /sbin/ldconfig

%postun -p /sbin/ldconfig

%files
%defattr(-,root,root,-)
# >> files
%doc COPYING README
%{_libdir}/gstreamer-1.0/libgstqt5videosink.so
%{_libdir}/libQt5GLib-2.0.so.*
%{_libdir}/libQt5GStreamer-1.0.so.*
%{_libdir}/libQt5GStreamerUi-1.0.so.*
%{_libdir}/libQt5GStreamerUtils-1.0.so.*
%{_libdir}/libQt5GStreamerQuick-1.0.so.*
%{_libdir}/qt5/qml/QtGStreamer/
# << files

%files devel
%defattr(-,root,root,-)
# >> files devel
%doc HACKING
%{_includedir}/Qt5GStreamer
%{_libdir}/cmake/Qt5GStreamer
%{_libdir}/libQt5GLib-2.0.so
%{_libdir}/libQt5GStreamer-1.0.so
%{_libdir}/libQt5GStreamerUi-1.0.so
%{_libdir}/libQt5GStreamerUtils-1.0.so
%{_libdir}/libQt5GStreamerQuick-1.0.so
%{_libdir}/pkgconfig/Qt5GLib-2.0.pc
%{_libdir}/pkgconfig/Qt5GStreamer-1.0.pc
%{_libdir}/pkgconfig/Qt5GStreamerUi-1.0.pc
%{_libdir}/pkgconfig/Qt5GStreamerUtils-1.0.pc
%{_libdir}/pkgconfig/Qt5GStreamerQuick-1.0.pc
# << files devel

